### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by joseggink** [joseggink/VRNL#1]
Bugfix 1

**Comment by joseggink** [comment]
Learning...

**Comment by DefV** [comment]
Opgelost.. Like a boss!

**Comment by joseggink** [comment]
Check!

Dient de rest van de groep zich gewoon aan te melden bij Guthub op de normale manier?

Goed weekend

Van: Jan De Poorter [mailto:notifications@github.com]
Verzonden: donderdag 7 april 2016 11:30
Aan: joseggink/VRNL
CC: Jos Eggink
Onderwerp: Re: [joseggink/VRNL] Test (#1)

Opgelost.. Like a boss!
